name: Accessibility Tests 

on: push

jobs:
  mix-test:
    name: Run application tests to generate HTML files
    runs-on: ubuntu-20.04
    env:
      MIX_ENV: test

    services:
      db:
        image: postgres
        ports: ["5432:5432"]
        env:
          POSTGRES_USER: postgres
          POSTGRES_PASSWORD: postgres
          POSTRGES_DB: launch_cart_test
        options: >-
          --health-cmd pg_isready
          --health-interval 10s
          --health-timeout 5s
          --health-retries 5

    steps:
      - name: Checkout Project
        uses: actions/checkout@v3
      - name: Setup App
        uses: ./.github/workflows/setup
      - name: Run Application Tests
        uses: ./.github/workflows/app_test
      - uses: actions/upload-artifact@v3
        with:
          name: html_files
          path: test/axe_html/

  axe-test:
    needs: mix-test
    name: Run Accessibility Tests
    runs-on: ubuntu-20.04
    env:
      MIX_ENV: test
    steps:
      - name: Checkout Project
        uses: actions/checkout@v3
      - name: Setup App
        uses: ./.github/workflows/setup
      - name: Download html files from mix test
        uses: actions/download-artifact@v3
        with:
          name: html_files
          path: test/axe_html/
      - name: Pa11y Tests
        run: mix excessibility

